
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Poppins } from "next/font/google";
import "./globals.css";
import { Footer, Navbar } from "@/components";
const inter = Inter({ subsets: ["latin"] });

const poppins = Poppins({
  weight: "400",
  subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <div className="w-full flex justify-center bg-white shadow-md"> <Navbar/></div>
        {children}
         <div className="w-full flex justify-center items-end bg-gray-900 pt-10"><Footer/></div>
        </body>
    </html>
  );
}
